---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: acr-auth
spec:
  encryptedData:
    .dockerconfigjson: AgCfTcIOW3ieRUNd6FWUZfQiI1FThImnWUVBPa0vAW+PF6mmF5BMujvHZQw1woQGZpsbpSvG65xy686A4jWMbGxV9j8LIVFE3dDDzjahMCSKoHMNCLXpXBVeMP8y8LhWUwO93c5Fu6YLAqMtdwA3o5L0MRK2l3ET4VzyqCJa5Zmj1vKMk9UDAIT9LQWxKhDN6Fgc2KGsdKaBZAS3Io9voe6E3O98A5P98B0KWyCcAL6Y5rBOgENUFH8GgHCy7H447qWsP9jaTOxoSeSaFXUvjvSGf9gAbGE/CU1m6FLxUM1jKaVBdjxHv0+5Q4yK3RFzQM90FJC7Sn1d2tUMaSv4q7J4AuglTyqFcT3w48fUKjgemaFtmCQkpZki5c+Kr1Vdmkw1XC9+Mk676Z2KX3aadycOMeSVv0r4GDKY6IVW/PAltnRZnp0q1pR58LISaAgV0nw3bMY7mROYcwwzSeJgwi8W0/CIl+gq3uMqrA9H/YJm4FNEbsf4vXBuSlNlEP95ZtGNNY9OMOTBjj7cVphgVQ9IRTrA2MeBFp7R8hNcOSWISjntsAQEoGtSZqsV7QT6a5ZQ4eYZTxmmy7QhLV7Rh81Teemw8eBgdr/YcLrKNKJJgHWopYszfSelMeKa5sG//S3ciPM8/5h1lFHW2nTKr07xMsrjyvwe56EBUEvWVQedZAxq4S59+4pl27BVH1TY+5/ucuqkKzIaVIwsq95AjJVQjJixADhhfJopUu2JnZmEYHnAhEF9dvzohAzIBJR2zcv+z4nlKeJraeztvsCj+aUdSRJcmKk0x05Qt4awKYy4u07UBrkVTLYQfuj+0Gc7LUHA8dTl5DnuNpr1cpjXxzgcVcVBmFSHHcoa8Mf9bnN7xrL8xE2iUV1zK/ctI0zULLpdfIgRfTs2YeyeOux8ZYHtVRi+tRQYVUgTZS15FOVd4vqjZ5wKidzLfn9tV25iImtvKEVZXLFBZgdV1A+QdkOnyu4/QJ+tperrCo5zQL8PKYY+Qg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: acr-auth
    type: kubernetes.io/dockerconfigjson
