
{{- range .Values.chatbots }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.config.namespace }}
  labels:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/version: {{ .image.tag }}
    app.kubernetes.io/component: chatbot
    app.kubernetes.io/part-of: chatbot-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .name }}
    spec:
      containers:
      - name: {{ .name }}
        image: {{ .image.repository }}:{{ .image.tag }}
        resources:
          {{- toYaml .resources | nindent 10 }}
        ports:
        - containerPort: {{ .service.targetPort }}
        {{- if .env }}
        env:
        {{- range .env }}
        - name: {{ .name }}
          valueFrom:
            secretKeyRef:
              name: {{ .secretName }}
              key: {{ .secretKey }}
        {{- end }}
        {{- end }}
        {{- if .configmap }}
        volumeMounts:
        - name: quarkus-config-volume
          mountPath: /work/config
        {{- end }}
        livenessProbe:
          httpGet:
            path: {{ .probes.liveness.path }}
            port: {{ .service.targetPort }}
          initialDelaySeconds: {{ .probes.liveness.initialDelaySeconds | default 30 }}
          periodSeconds: {{ .probes.liveness.periodSeconds | default 10 }}
          timeoutSeconds: {{ .probes.liveness.timeoutSeconds | default 5 }}
          failureThreshold: {{ .probes.liveness.failureThreshold | default 3 }}
        readinessProbe:
          httpGet:
            path: {{ .probes.readiness.path | default "/health" }}
            port: {{ .service.targetPort }}
          initialDelaySeconds: {{ .probes.readiness.initialDelaySeconds | default 10 }}
          periodSeconds: {{ .probes.readiness.periodSeconds | default 5 }}
          timeoutSeconds: {{ .probes.readiness.timeoutSeconds | default 3 }}
          failureThreshold: {{ .probes.readiness.failureThreshold | default 3 }}
        imagePullPolicy: {{ .image.pullPolicy | default "Always" }}
      {{- if .configmap }}
      volumes:
      - name: quarkus-config-volume
        configMap:
          name: {{ .name }}
      {{- end }}

      imagePullSecrets:
      - name: acr-auth
{{- end }}