{{- range .Values.chatbots }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.config.namespace }}
  labels:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/version: {{ .image.tag }}
    app.kubernetes.io/component: chatbot
    app.kubernetes.io/part-of: chatbot-system
spec:
  selector:
    app.kubernetes.io/name: {{ .name }}
  ports:
  - port: {{ .service.port }}
    targetPort: {{ .service.targetPort }}
  type: {{ .service.type | default "ClusterIP" }}
{{- end }}