config:
  namespace: prod
  acrBaseRepository: fs25group13.azurecr.io

chatbots:
  - name: connecting-worlds
    image:
      repository: fs25group13.azurecr.io/connecting-worlds
      tag: v1.0.4
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "1m"
        memory: "150Mi"
      limits:
        cpu: "2m"
        memory: "300Mi"
    service:
      port: 80
      targetPort: 8080
    configmap:
      fastifyUrl: chat?message=
      dotnetUrl: chat?message=
    probes:
      liveness:
        path: /q/health/live
        initialDelaySeconds: 300
        periodSeconds: 30
        timeoutSeconds: 10
        failureThreshold: 5
      readiness:
        path: /q/health/ready
        initialDelaySeconds: 300
        periodSeconds: 30
        timeoutSeconds: 10
        failureThreshold: 5

  - name: dotnet-chatbot
    image:
      repository: fs25group13.azurecr.io/dotnet-chatbot
      tag: v1.0.1
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "1m"
        memory: "60Mi"
      limits:
        cpu: "2m"
        memory: "120Mi"
    service:
      port: 80
      targetPort: 8080
    env:
      - name: HuggingFace__ApiKey
        secretName: chatbot-api-keys
        secretKey: dotnet-chatbot-api-key
    probes:
      liveness:
        path: /liveness
        initialDelaySeconds: 60
        periodSeconds: 20
        timeoutSeconds: 5
        failureThreshold: 3
      readiness:
        path: /readiness
        initialDelaySeconds: 60
        periodSeconds: 20
        timeoutSeconds: 5
        failureThreshold: 3

  - name: fastify-chatbot
    image:
      repository: fs25group13.azurecr.io/fastify-chatbot
      tag: v1.0.3
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "1m"
        memory: "60Mi"
      limits:
        cpu: "2m"
        memory: "120Mi"
    service:
      port: 80
      targetPort: 3000
    env:
      - name: LLM_API_KEY
        secretName: chatbot-api-keys
        secretKey: fastify-chatbot-api-key
    probes:
      liveness:
        path: /healthz
        initialDelaySeconds: 60
        periodSeconds: 20
        timeoutSeconds: 5
        failureThreshold: 3
      readiness:
        path: /readyz
        initialDelaySeconds: 60
        periodSeconds: 20
        timeoutSeconds: 5
        failureThreshold: 3