config:
  namespace: staging
  acrBaseRepository: fs25group13.azurecr.io

chatbots:
  - name: connecting-worlds
    image:
      repository: fs25group13.azurecr.io/connecting-worlds
      tag: stable
      pullPolicy: Always
    resources:
      requests:
        cpu: "1m"
        memory: "125Mi"
      limits:
        cpu: "2m"
        memory: "250Mi"
    service:
      port: 80
      targetPort: 8080
    configmap:
      fastifyUrl: chat?message=
      dotnetUrl: chat?message=

  - name: dotnet-chatbot
    image:
      repository: fs25group13.azurecr.io/dotnet-chatbot
      tag: stable
      pullPolicy: Always
    resources:
      requests:
        cpu: "1m"
        memory: "60Mi"
      limits:
        cpu: "2m"
        memory: "120Mi"
    service:
      port: 80
      targetPort: 8080
    env:
      - name: HuggingFace__ApiKey
        secretName: chatbot-api-keys
        secretKey: dotnet-chatbot-api-key

  - name: fastify-chatbot
    image:
      repository: fs25group13.azurecr.io/fastify-chatbot
      tag: stable
      pullPolicy: Always
    resources:
      requests:
        cpu: "1m"
        memory: "60Mi"
      limits:
        cpu: "2m"
        memory: "120Mi"
    service:
      port: 80
      targetPort: 3000
    env:
      - name: LLM_API_KEY
        secretName: chatbot-api-keys
        secretKey: fastify-chatbot-api-key