defaultRules:
  rules:
    kubeScheduler: false
  disabled:
    KubeControllerManagerDown: true
    KubeSchedulerDown: true
    KubeMemoryOvercommit: true

kubeProxy:
  enabled: true
  service:
    enabled: true
    selector:
      component: kube-proxy

kubeControllerManager:
  enabled: false
  service:
    enabled: false
  serviceMonitor:
    enabled: false


kubeScheduler:
  enabled: false
  service:
    enabled: false
  serviceMonitor:
    enabled: false


prometheus:
  prometheusSpec:
    podMonitorSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelector: {}
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
