apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatbot-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@ssh.dev.azure.com:v3/fhnw-devops/fs25-group13/fs25-group13
    targetRevision: main
    path: chatbots
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false